//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CliningCompany.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.Reviews = new HashSet<Reviews>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ServiceId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string PickupAddress { get; set; }
        public System.DateTime PickupTime { get; set; }
        public string PaymentMethod { get; set; }
        public string Status { get; set; }
    
        public virtual Services Services { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Reviews> Reviews { get; set; }
    }
}
